backend:
  name: github
  repo: GongJiu-create/my-blog   # 例如: GongJiu-create/my-blog
  branch: main                         # 保持和你的主要分支保持一致

media_folder: source/images             # 图片会上传到 source/images
public_folder: /images                  # 访问图片时的路径

collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }